package com.habib.coronanews;

import java.util.HashMap;

public class Constant {
    public static HashMap<String,String> map = new HashMap<>();
    public static final String HOST = "covid-193.p.rapidapi.com";
    public static final String KEY = "2d9e07a4e8mshd5fa81d7e122d1bp1ed32bjsn3b734cfab37f";
    public static final String URL = "https://covid-193.p.rapidapi.com/statistics";
    public static final String NEWS_KEY = "655457aa51f444568e592ade394c78ec";
    public static final String NEWS_URL = "https://newsapi.org/v2/everything?q=COVID&sortBy=publishedAt&sources=bbc-news&apiKey=655457aa51f444568e592ade394c78ec&pageSize=50&page=1";
    public Constant (){
        map.put("Afghanistan","af");
        map.put("Åland Islands","ax");
        map.put("Albania","al");
        map.put("Algeria","dz");
        map.put("American Samoa","as");
        map.put("Andorra","ad");
        map.put("Angola","ao");
        map.put("Anguilla","ai");
        map.put("Antarctica","aq");
        map.put("Antigua and Barbuda","ag");
        map.put("Argentina","ar");
        map.put("Armenia","am");
        map.put("Aruba","aw");
        map.put("Australia","au");
        map.put("Austria","at");
        map.put("Azerbaijan","az");
        map.put("Bahamas","bs");
        map.put("Bahrain","bh");
        map.put("Bangladesh","bd");
        map.put("Barbados","bb");
        map.put("Belarus","by");
        map.put("Belgium","be");
        map.put("Belize","bz");
        map.put("Benin","bj");
        map.put("Bermuda","bm");
        map.put("Bhutan","bt");
        map.put("Bolivia, Plurinational State of","bo");
        map.put("Bonaire, Sint Eustatius and Saba","bq");
        map.put("Bosnia and Herzegovina","ba");
        map.put("Botswana","bw");
        map.put("Bouvet Island","bv");
        map.put("Brazil","br");
        map.put("British Indian Ocean Territory","io");
        map.put("Brunei Darussalam","bn");
        map.put("Bulgaria","bg");
        map.put("Burkina Faso","bf");
        map.put("Burundi","bi");
        map.put("Cambodia","kh");
        map.put("Cameroon","cm");
        map.put("Canada","ca");
        map.put("Cape Verde","cv");
        map.put("Cayman Islands","ky");
        map.put("Central African Republic","cf");
        map.put("Chad","td");
        map.put("Chile","cl");
        map.put("China","cn");
        map.put("Christmas Island","cx");
        map.put("Cocos (Keeling) Islands","cc");
        map.put("Colombia","co");
        map.put("Comoros","km");
        map.put("Congo","cg");
        map.put("Congo, the Democratic Republic of the","cd");
        map.put("Cook Islands","ck");
        map.put("Costa Rica","cr");
        map.put("Côte d'Ivoire","ci");
        map.put("Croatia","hr");
        map.put("Cuba","cu");
        map.put("Curaçao","cw");
        map.put("Cyprus","cy");
        map.put("Czech Republic","cz");
        map.put("Denmark","dk");
        map.put("Djibouti","dj");
        map.put("Dominica","dm");
        map.put("Dominican Republic","do");
        map.put("Ecuador","ec");
        map.put("Egypt","eg");
        map.put("El Salvador","sv");
        map.put("Equatorial Guinea","gq");
        map.put("Eritrea","er");
        map.put("Estonia","ee");
        map.put("Ethiopia","et");
        map.put("Falkland Islands (Malvinas)","fk");
        map.put("Faroe Islands","fo");
        map.put("Fiji","fj");
        map.put("Finland","fi");
        map.put("France","fr");
        map.put("French Guiana","gf");
        map.put("French Polynesia","pf");
        map.put("French Southern Territories","tf");
        map.put("Gabon","ga");
        map.put("Gambia","gm");
        map.put("Georgia","ge");
        map.put("Germany","de");
        map.put("Ghana","gh");
        map.put("Gibraltar","gi");
        map.put("Greece","gr");
        map.put("Greenland","gl");
        map.put("Grenada","gd");
        map.put("Guadeloupe","gp");
        map.put("Guam","gu");
        map.put("Guatemala","gt");
        map.put("Guernsey","gg");
        map.put("Guinea","gn");
        map.put("Guinea-Bissau","gw");
        map.put("Guyana","gy");
        map.put("Haiti","ht");
        map.put("Heard Island and McDonald Islands","hm");
        map.put("Holy See (Vatican City State)","va");
        map.put("Honduras","hn");
        map.put("Hong Kong","hk");
        map.put("Hungary","hu");
        map.put("Iceland","is");
        map.put("India","in");
        map.put("Indonesia","id");
        map.put("Iran","ir");
        map.put("Iraq","iq");
        map.put("Ireland","ie");
        map.put("Isle of Man","im");
        map.put("Israel","il");
        map.put("Italy","it");
        map.put("Jamaica","jm");
        map.put("Japan","jp");
        map.put("Jersey","je");
        map.put("Jordan","jo");
        map.put("Kazakhstan","kz");
        map.put("Kenya","ke");
        map.put("Kiribati","ki");
        map.put("Korea, Democratic People's Republic of","kp");
        map.put("Korea, Republic of","kr");
        map.put("Kuwait","kw");
        map.put("Kyrgyzstan","kg");
        map.put("Lao People's Democratic Republic","la");
        map.put("Latvia","lv");
        map.put("Lebanon","lb");
        map.put("Lesotho","ls");
        map.put("Liberia","lr");
        map.put("Libya","ly");
        map.put("Liechtenstein","li");
        map.put("Lithuania","lt");
        map.put("Luxembourg","lu");
        map.put("Macao","mo");
        map.put("Macedonia, the Former Yugoslav Republic of","mk");
        map.put("Madagascar","mg");
        map.put("Malawi","mw");
        map.put("Malaysia","my");
        map.put("Maldives","mv");
        map.put("Mali","ml");
        map.put("Malta","mt");
        map.put("Marshall Islands","mh");
        map.put("Martinique","mq");
        map.put("Mauritania","mr");
        map.put("Mauritius","mu");
        map.put("Mayotte","yt");
        map.put("Mexico","mx");
        map.put("Micronesia, Federated States of","fm");
        map.put("Moldova, Republic of","md");
        map.put("Monaco","mc");
        map.put("Mongolia","mn");
        map.put("Montenegro","me");
        map.put("Montserrat","ms");
        map.put("Morocco","ma");
        map.put("Mozambique","mz");
        map.put("Myanmar","mm");
        map.put("Namibia","na");
        map.put("Nauru","nr");
        map.put("Nepal","np");
        map.put("Netherlands","nl");
        map.put("New Caledonia","nc");
        map.put("New Zealand","nz");
        map.put("Nicaragua","ni");
        map.put("Niger","ne");
        map.put("Nigeria","ng");
        map.put("Niue","nu");
        map.put("Norfolk Island","nf");
        map.put("Northern Mariana Islands","mp");
        map.put("Norway","no");
        map.put("Oman","om");
        map.put("Pakistan","pk");
        map.put("Palau","pw");
        map.put("Palestine, State of","ps");
        map.put("Panama","pa");
        map.put("Papua New Guinea","pg");
        map.put("Paraguay","py");
        map.put("Peru","pe");
        map.put("Philippines","ph");
        map.put("Pitcairn","pn");
        map.put("Poland","pl");
        map.put("Portugal","pt");
        map.put("Puerto Rico","pr");
        map.put("Qatar","qa");
        map.put("Réunion","re");
        map.put("Romania","ro");
        map.put("Russia","ru");
        map.put("Rwanda","rw");
        map.put("Saint Barthélemy","bl");
        map.put("Saint Helena, Ascension and Tristan da Cunha","sh");
        map.put("Saint Kitts and Nevis","kn");
        map.put("Saint Lucia","lc");
        map.put("Saint Martin (French part)","mf");
        map.put("Saint Pierre and Miquelon","pm");
        map.put("Saint Vincent and the Grenadines","vc");
        map.put("Samoa","ws");
        map.put("San Marino","sm");
        map.put("Sao Tome and Principe","st");
        map.put("Saudi Arabia","sa");
        map.put("Senegal","sn");
        map.put("Serbia","rs");
        map.put("Seychelles","sc");
        map.put("Sierra Leone","sl");
        map.put("Singapore","sg");
        map.put("Sint Maarten (Dutch part)","sx");
        map.put("Slovakia","sk");
        map.put("Slovenia","si");
        map.put("Solomon Islands","sb");
        map.put("Somalia","so");
        map.put("South Africa","za");
        map.put("South Georgia and the South Sandwich Islands","gs");
        map.put("South Sudan","ss");
        map.put("Spain","es");
        map.put("Sri Lanka","lk");
        map.put("Sudan","sd");
        map.put("Suriname","sr");
        map.put("Svalbard and Jan Mayen","sj");
        map.put("Swaziland","sz");
        map.put("Sweden","se");
        map.put("Switzerland","ch");
        map.put("Syrian Arab Republic","sy");
        map.put("Taiwan, Province of China","tw");
        map.put("Tajikistan","tj");
        map.put("Tanzania, United Republic of","tz");
        map.put("Thailand","th");
        map.put("Timor-Leste","tl");
        map.put("Togo","tg");
        map.put("Tokelau","tk");
        map.put("Tonga","to");
        map.put("Trinidad and Tobago","tt");
        map.put("Tunisia","tn");
        map.put("Turkey","tr");
        map.put("Turkmenistan","tm");
        map.put("Turks and Caicos Islands","tc");
        map.put("Tuvalu","tv");
        map.put("Uganda","ug");
        map.put("Ukraine","ua");
        map.put("UAE","ae");
        map.put("UK","gb");
        map.put("USA","us");
        map.put("United States Minor Outlying Islands","um");
        map.put("Uruguay","uy");
        map.put("Uzbekistan","uz");
        map.put("Vanuatu","vu");
        map.put("Venezuela, Bolivarian Republic of","ve");
        map.put("Viet Nam","vn");
        map.put("Virgin Islands, British","vg");
        map.put("Virgin Islands, U.S.","vi");
        map.put("Wallis and Futuna","wf");
        map.put("Western Sahara","eh");
        map.put("Yemen","ye");
        map.put("Zambia","zm");
        map.put("Zimbabwe","zw");

    }
}
